# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "hugo-pabotesu-theme"
license = "MIT"
licenselink = "https://github.com/minetaro12/hugo-osan-theme/blob/master/LICENSE"
description = ""
homepage = ""
#tags = []
#features = []
min_version = "0.109.0"

[author]
  name = "pabotesu"
  homepage = ""

# If porting an existing theme
# [original]
#  name = ""
#  homepage = ""
#  repo = ""
